// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

#pragma once

#include "vec/data_types/data_type_number.h"
#include "vec/functions/function.h"

namespace doris::vectorized {

/// Computes Paimon's bucket id for a row using the same algorithm as the
/// Paimon Java SDK (DefaultBucketFunction + MurmurHashUtils).
///
/// Usage in SQL (generated by FE, never user-visible):
///   paimon_bucket_id(bucket_key, num_buckets)  →  INT
///
/// Phase 2a type support: single INT / BIGINT bucket key column.
/// Multi-column keys and variable-length types fall back to GATHER.
class FunctionPaimonBucketId : public IFunction {
public:
    static constexpr auto name = "paimon_bucket_id";

    static FunctionPtr create() { return std::make_shared<FunctionPaimonBucketId>(); }

    String get_name() const override { return name; }

    size_t get_number_of_arguments() const override { return 2; }

    DataTypePtr get_return_type_impl(const DataTypes& /*arguments*/) const override {
        return std::make_shared<DataTypeInt32>();
    }

    Status execute_impl(FunctionContext* context, Block& block, const ColumnNumbers& arguments,
                        uint32_t result, size_t input_rows_count) const override;
};

} // namespace doris::vectorized
